### ISSUE TITLE
Fix video fit on mobile

### ISSUE THREAD

**Issue by ElsieNoel** [alansouzati/zozu-sponsor-portal#9]
The video under the "our organization" tab bleeds off the mobile device screen.

**Comment by alansouzati** [comment]
This is now fixed. I had to deal with a big unexpected problem. I'm going to explain here, it will be a bit technical, but I would like to share that so that you don't face this problem.

Consider these two examples:

```
<iframe src="...."></iframe>
```

and

```
<iframe src="..." />
```

These two codes are supposed to work exactly the same. The difference between them is that the second uses what is called a self closing tag.

When I tried to plug that in the site the page broke completely :(

I think it is a good idea to report this problem with the site owner.

I did not have a copy, so moving forward I will always copy the page before changing it :)
